/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package puissance4;

import java.util.Random;

/**
 *
 * @author matti
 */
public class fenetredeJeu extends javax.swing.JFrame {

    /**
     * Creates new form fenetredeJeu
     */
    
    private Joueur[] listeJoueur = new Joueur[2];
    private Joueur joueurCourant = listeJoueur[0];
    private PlateauDeJeu plateau = new PlateauDeJeu();
    
    
    public fenetredeJeu() {
        initComponents();
        panneau_infojoueur.setVisible(false);
        panneau_infopartie.setVisible(false);
        
        for(int i=5;i>=0;i--){
            for(int j=0;j<7;j++){
                cellule_graphique cellGraph = new cellule_graphique(plateau.grille[i][j]);
                
               cellGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
                CelluledeGrille c = cellGraph.celluleAssociée;
                if(c.Jetoncourant ==null)return;
                if(c.Jetoncourant.lireCouleur().equals(joueurCourant.lireCouleur())){
                    message.setText("le joueur" + joueurCourant.nom + "récupère un jeton");
                }
                else{
                 message.setText("le joueur" + joueurCourant.nom + "à désintégré un jeton");
                }
                message.setText("un bouton à été cliqué");
                
            }
        });
                panneau_grille.add(cellGraph);
            }
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneau_creationpartie = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomjoueur1 = new javax.swing.JTextField();
        nomjoueur2 = new javax.swing.JTextField();
        btn_star = new javax.swing.JButton();
        panneau_infojoueur = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_nomj1 = new javax.swing.JLabel();
        lbl_coulj2 = new javax.swing.JLabel();
        lbl_coulj1 = new javax.swing.JLabel();
        lbl_nomj2 = new javax.swing.JLabel();
        lbl_desj1 = new javax.swing.JLabel();
        lbl_desj2 = new javax.swing.JLabel();
        panneau_infopartie = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lbl_nom_jcourant = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        btn_col1 = new javax.swing.JButton();
        btn_col2 = new javax.swing.JButton();
        btn_col3 = new javax.swing.JButton();
        btn_col4 = new javax.swing.JButton();
        btn_col5 = new javax.swing.JButton();
        btn_col6 = new javax.swing.JButton();
        btn_col7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 672, 576));

        panneau_creationpartie.setBackground(new java.awt.Color(0, 153, 153));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("nom joueur 1");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("nom joueur 2");

        nomjoueur1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nomjoueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomjoueur1ActionPerformed(evt);
            }
        });

        nomjoueur2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nomjoueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomjoueur2ActionPerformed(evt);
            }
        });

        btn_star.setText("démarrer partie");
        btn_star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_starActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneau_creationpartieLayout = new javax.swing.GroupLayout(panneau_creationpartie);
        panneau_creationpartie.setLayout(panneau_creationpartieLayout);
        panneau_creationpartieLayout.setHorizontalGroup(
            panneau_creationpartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_creationpartieLayout.createSequentialGroup()
                .addGroup(panneau_creationpartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panneau_creationpartieLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panneau_creationpartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panneau_creationpartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomjoueur2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomjoueur1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panneau_creationpartieLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_star)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panneau_creationpartieLayout.setVerticalGroup(
            panneau_creationpartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_creationpartieLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panneau_creationpartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomjoueur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneau_creationpartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomjoueur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_star)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(panneau_creationpartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 300, 140));

        panneau_infojoueur.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("STCaiyun", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INFOS   JOUEURS");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Joueur 1 :");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Couleur :");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre De Désintégrateurs :");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Joueur 2 :");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Couleur :");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nombre De Désintégrateurs:");

        lbl_nomj1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_nomj1.setForeground(new java.awt.Color(255, 255, 255));

        lbl_coulj2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_coulj2.setForeground(new java.awt.Color(255, 255, 255));

        lbl_coulj1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_coulj1.setForeground(new java.awt.Color(255, 255, 255));

        lbl_nomj2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_nomj2.setForeground(new java.awt.Color(255, 255, 255));

        lbl_desj1.setForeground(new java.awt.Color(255, 255, 255));

        lbl_desj2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panneau_infojoueurLayout = new javax.swing.GroupLayout(panneau_infojoueur);
        panneau_infojoueur.setLayout(panneau_infojoueurLayout);
        panneau_infojoueurLayout.setHorizontalGroup(
            panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_infojoueurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panneau_infojoueurLayout.createSequentialGroup()
                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panneau_infojoueurLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panneau_infojoueurLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_desj2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneau_infojoueurLayout.createSequentialGroup()
                                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_nomj2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_coulj2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneau_infojoueurLayout.createSequentialGroup()
                                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_coulj1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nomj1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panneau_infojoueurLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(lbl_desj1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panneau_infojoueurLayout.setVerticalGroup(
            panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_infojoueurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panneau_infojoueurLayout.createSequentialGroup()
                        .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lbl_nomj1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel12))
                    .addGroup(panneau_infojoueurLayout.createSequentialGroup()
                        .addComponent(lbl_coulj1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_desj1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nomj2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(lbl_coulj2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panneau_infojoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lbl_desj2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        getContentPane().add(panneau_infojoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 300, 260));

        panneau_infopartie.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("STCaiyun", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INFOS   JEUX");

        lbl_nom_jcourant.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lbl_nom_jcourant.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Joueur  courant :");

        message.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panneau_infopartieLayout = new javax.swing.GroupLayout(panneau_infopartie);
        panneau_infopartie.setLayout(panneau_infopartieLayout);
        panneau_infopartieLayout.setHorizontalGroup(
            panneau_infopartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_infopartieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panneau_infopartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panneau_infopartieLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panneau_infopartieLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(lbl_nom_jcourant, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panneau_infopartieLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panneau_infopartieLayout.setVerticalGroup(
            panneau_infopartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_infopartieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneau_infopartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(lbl_nom_jcourant, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panneau_infopartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 300, 120));

        btn_col1.setLabel("1");
        btn_col1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btn_col2.setText("2");
        btn_col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 50, -1, -1));

        btn_col3.setText("3");
        btn_col3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col3, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 50, -1, -1));

        btn_col4.setLabel("4");
        btn_col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 50, -1, -1));

        btn_col5.setLabel("5");
        btn_col5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col5, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 50, -1, -1));

        btn_col6.setLabel("6");
        btn_col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        btn_col7.setLabel("7");
        btn_col7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col7, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 50, -1, -1));

        setBounds(0, 0, 1237, 749);
    }// </editor-fold>//GEN-END:initComponents

    private void nomjoueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomjoueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomjoueur1ActionPerformed

    private void nomjoueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomjoueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomjoueur2ActionPerformed

    private void btn_col1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col1ActionPerformed
         
         jouerdanscolonne(0);
         if(plateau.colonneRemplie(0)==true) btn_col1.setEnabled(false);
         joueursuivant ();
    }//GEN-LAST:event_btn_col1ActionPerformed

    private void btn_col3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col3ActionPerformed
        
        jouerdanscolonne(2);
        if(plateau.colonneRemplie(2)==true) btn_col3.setEnabled(false);
        joueursuivant ();
    }//GEN-LAST:event_btn_col3ActionPerformed

    public boolean jouerdanscolonne(int indice_colonne){
        
        
        boolean resultatAction;
      
                
                
                resultatAction = plateau.ajouterJetonDansColonnes(joueurCourant,indice_colonne);
                panneau_grille.repaint();
                
                lbl_desj1.setText(listeJoueur[0].lirenombreDesintegrateurs()+ "");
                 lbl_desj2.setText(listeJoueur[1].lirenombreDesintegrateurs()+ "");
                 
                 boolean vict_j1 = plateau.etreGagnantePourCouleur(listeJoueur[0].lireCouleur());
                   boolean vict_j2 = plateau.etreGagnantePourCouleur(listeJoueur[1].lireCouleur());
                   
                   if (vict_j1 &&! vict_j2)message.setText("victoire de joueur 1");
                    if (vict_j2 &&! vict_j1)message.setText("victoire de joueur 2");
                    if (vict_j1 &&  vict_j2){
                        if(joueurCourant==listeJoueur[0]) message.setText("victoire de joueur 1");
                        else message.setText("victoire de joueur 2");
                    }
                    
                         
                         
                
                if (resultatAction==true){           
                    return true;
                }
                else {            
                    return false;
                }
                
                
        
    }
    private void btn_starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_starActionPerformed
        panneau_infojoueur.setVisible(true);
        panneau_infopartie.setVisible(true); 
        initialiserPartie();
        panneau_grille.repaint();
      //btn_star.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_starActionPerformed

    private void btn_col7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col7ActionPerformed
       
       jouerdanscolonne(6);
       if(plateau.colonneRemplie(6)==true) btn_col7.setEnabled(false);
       joueursuivant ();
    }//GEN-LAST:event_btn_col7ActionPerformed

    private void btn_col2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col2ActionPerformed
        
      jouerdanscolonne(1);
      if(plateau.colonneRemplie(1)==true) btn_col2.setEnabled(false);
         joueursuivant ();
    }//GEN-LAST:event_btn_col2ActionPerformed

    private void btn_col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col4ActionPerformed
        
        jouerdanscolonne(3);
        if(plateau.colonneRemplie(3)==true) btn_col4.setEnabled(false);
        joueursuivant ();
    }//GEN-LAST:event_btn_col4ActionPerformed

    private void btn_col5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col5ActionPerformed
        
         jouerdanscolonne(4);
         if(plateau.colonneRemplie(4)==true) btn_col5.setEnabled(false);
         joueursuivant ();
    }//GEN-LAST:event_btn_col5ActionPerformed

    private void btn_col6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col6ActionPerformed
       
        jouerdanscolonne(5);
        if(plateau.colonneRemplie(5)==true) btn_col6.setEnabled(false);
        joueursuivant ();
    }//GEN-LAST:event_btn_col6ActionPerformed

    public void joueursuivant (){
        if(joueurCourant == listeJoueur[0]){
           joueurCourant = listeJoueur[1];
        }
        else {
          joueurCourant = listeJoueur[0];
          
        }
        lbl_nom_jcourant.setText(joueurCourant.nom);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetredeJeu().setVisible(true);
            }
        });
        
        
    }
    
    public void attribuerCouleurAuxJoueurs() {
        double a = Math.random();
        if (a > 0.5) {
            listeJoueur[0].affecterCouleur("jaune");
            listeJoueur[1].affecterCouleur("rouge");
        } else {
            listeJoueur[0].affecterCouleur("rouge");
            listeJoueur[1].affecterCouleur("jaune");

        }
    }
        
         public void creerEtAffecterJeton(Joueur joueur) {
        for (int i = 0; i < 30; i++) {
             joueur.ajouterJeton(new Jeton(joueur.lireCouleur()));
        
        }
         }
        
        public void placerTrouNoirEtDesintegrateur() {
        int i=0;
        while (i!=3) {
            Random r = new Random();
            int a = r.nextInt(6);
            int b = r.nextInt(7);
            if (plateau.presenceTrouNoir(a, b) == false && plateau.presenceDesintegrateur(a, b) == false) {
                plateau.placerDesintegrateur(a, b);
                plateau.placerTrouNoir(a, b);
                i+=1;

            }
        }
        int j=0;
        while(j!=2) {
            Random r = new Random();
            int c = r.nextInt(6);
            int d = r.nextInt(7);
            if (plateau.presenceTrouNoir(c, d) == false && plateau.presenceDesintegrateur(c, d) == false) {
                plateau.placerTrouNoir(c, d);
                j+=1;
            }
        }
        int k = 0;
        while(k!=2) {
            Random r = new Random();
            int e = r.nextInt(6);
            int f = r.nextInt(7);
            if (plateau.presenceTrouNoir(e, f) == false && plateau.presenceDesintegrateur(e, f) == false) {
                plateau.placerDesintegrateur(e, f);
                k+=1;
            }

        }
    }
    
    public void initialiserPartie() {
                placerTrouNoirEtDesintegrateur();

        String nomJ1= nomjoueur1.getText();
        Joueur J1 = new Joueur(nomJ1);
        
        String nomJ2 = nomjoueur2.getText();
        Joueur J2 = new Joueur(nomJ2);
        listeJoueur[0] = J1;
        listeJoueur[1] = J2;
        
        System.out.println("z");
        
        
        attribuerCouleurAuxJoueurs(); //on donne une couleur au différents joueurs
        creerEtAffecterJeton(listeJoueur[0]); // on donne les jetons au joueur 1 
        creerEtAffecterJeton(listeJoueur[1]); // on donne les jetons au joueur 2
        
        lbl_nomj1.setText(nomJ1);
        lbl_nomj2.setText(nomJ2);
        lbl_coulj1.setText(J1.lireCouleur());
        lbl_coulj2.setText(J2.lireCouleur());
        lbl_desj1.setText(J1.lirenombreDesintegrateurs() + "");
        lbl_desj2.setText(J2.lirenombreDesintegrateurs() + "");
         
        
          Joueur JoueurCourant = listeJoueur[0];   
        lbl_nom_jcourant.setText(JoueurCourant.nom);
       
        
        
        
       
        
        

    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_col1;
    private javax.swing.JButton btn_col2;
    private javax.swing.JButton btn_col3;
    private javax.swing.JButton btn_col4;
    private javax.swing.JButton btn_col5;
    private javax.swing.JButton btn_col6;
    private javax.swing.JButton btn_col7;
    private javax.swing.JButton btn_star;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_start1;
    private javax.swing.JPanel creationPartie;
    private javax.swing.JPanel creationPartie1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_coulj1;
    private javax.swing.JLabel lbl_coulj2;
    private javax.swing.JLabel lbl_desj1;
    private javax.swing.JLabel lbl_desj2;
    private javax.swing.JLabel lbl_nom_jcourant;
    private javax.swing.JLabel lbl_nomj1;
    private javax.swing.JLabel lbl_nomj2;
    private javax.swing.JLabel message;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JTextField nom_joueur3;
    private javax.swing.JTextField nom_joueur4;
    private javax.swing.JTextField nomjoueur1;
    private javax.swing.JTextField nomjoueur2;
    private javax.swing.JPanel panneau_creationpartie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_infojoueur;
    private javax.swing.JPanel panneau_infopartie;
    // End of variables declaration//GEN-END:variables
}
